### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/gofail#33]
Let's release the first formal version v0.1.0, and update etcd to pin to the specific version.

We start to track changes in https://github.com/etcd-io/gofail/blob/master/CHANGELOG.md 

cc @ptabor @serathius @spzala 

WDYT?

**Comment by ahrtr** [comment]
@serathius @spzala I suggest to release gofail 0.1.0, so that all users (e.g etcd) depend on a tag version.

**Comment by spzala** [comment]
+1 sounds good to me. Thanks @ahrtr

**Comment by serathius** [comment]
One thought, we plan a couple of breaking changes to get gofail useful for linearizability tests.  One example is removing package name from the failpoint name as it makes moving code an incompatible change, complicating multi version testing. 

There are a lot of rough edges and proper integration with linearizability tests should allow us to smooth them out. Possibly for v0.1.0 release smooth experience is not needed, however tagging release is also technically not nesesery.

You could argue that package didn't required any changes before. Problem is that it was not well utilized before. For example whole `gofail-go` feature was broken. I would wait with release until we have more experience with using it in practice.

**Comment by ahrtr** [comment]
> we plan a couple of breaking changes

Could you raise issues in this repo to track the changes you proposed?



> For example whole `gofail-go` feature was broken

This might not be a good example. I wouldn't say `gofail-go` was broken. The only reason why I removed it is that it complicate the design & implementation without obvious benefit.

**Comment by ahrtr** [comment]
I think it's time to release a tag version for gofail. We have already supported setting multiple failpoints. 

Please let me know if you have any concern.

**Comment by serathius** [comment]
Would like to get https://github.com/etcd-io/etcd/issues/14727 in. In introduced breaking change in name of failpoints. Let me know if we should accelerate work on it.

**Comment by ahrtr** [comment]
All planned tasks/PRs are done. It's time to create the `v0.1.0` tag

**Comment by ahrtr** [comment]
https://github.com/etcd-io/gofail/releases/tag/v0.1.0
