### ISSUE TITLE
Implement `gofail version` command

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/gofail#34]
I expect `gofail version` could display the info similar to etcd.

```
$ etcd --version
etcd Version: 3.5.5
Git SHA: 19002cfc6
Go Version: go1.16.15
Go OS/Arch: darwin/amd64
```

**Comment by ramil600** [comment]
I will start working on it

**Comment by ramil600** [comment]
submitted #35

**Comment by ahrtr** [comment]
Done in https://github.com/etcd-io/gofail/pull/35 and https://github.com/etcd-io/gofail/pull/36
