### ISSUE TITLE
Release gofail v0.2.0

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/gofail#72]
After https://github.com/etcd-io/gofail/pull/69 gets merged, we are going to release v0.2.0.

cc @ArkaSaha30 @henrybear327 @serathius

**Comment by ahrtr** [comment]
Done https://github.com/etcd-io/gofail/releases/tag/v0.2.0

@ArkaSaha30 @henrybear327 Please feel free to bump gofail to v0.2.0 for etcd. thx

**Comment by ArkaSaha30** [comment]
Sure @ahrtr , thank you

**Comment by henrybear327** [comment]
Thanks @ahrtr!

**Comment by ArkaSaha30** [comment]
@ahrtr do we need to bump in `bbolt` and `raft` as well?

**Comment by ahrtr** [comment]
> @ahrtr do we need to bump in `bbolt` and `raft` as well?

yes for bbolt. 

raft doesn't depend on gofail for now.
